image: Visual Studio 2019

environment:
  matrix:
  - job_name: Package

platform: 
  - x86
  - x64
 
configuration: Release

before_build:
  - findstr /V "{48C5258A-FA49-4173-AEE5-0FCA5190DFF2}.Debug {48C5258A-FA49-4173-AEE5-0FCA5190DFF2}.Release" .\ReClass.NET.sln > cleaned.sln # This removes the .Unix project from the solution another option would be to create a custom target inside the project
  - rm ReClass.NET.sln
  - nuget restore # restore nuget dependencies

# Build the solution with the name cleaned.sln
build:
  project: cleaned.sln
  verbosity: minimal

# job-specific configurations
for:
  -
    matrix:
      only:
        - job_name: Package
    build_script:
    - echo Job 1

# Package the builded files into a zip and push as artifacts
after_build:
  - cd %APPVEYOR_BUILD_FOLDER% # CD into the cloned project folder
  - cd Bin # CD into  Bin
  - cd Release # CD into Release
  - set BUILD_ARCHIVE=%APPVEYOR_PROJECT_NAME%-%CONFIGURATION%-%PLATFORM%.zip # Set our output archive as projectname-(Debug|Release)-(x86|x64)
  - cmd: 7z a -r %BUILD_ARCHIVE% *.dll *.exe # Add all exe and dll files to our archive
  - appveyor PushArtifact %BUILD_ARCHIVE% # Upload the archive as an artifact